name: Deploy on LocalStack 

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # “At 00:00 on Sunday.”
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  cdk:
    name: Setup infrastructure using CDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Install lstk
        run: |
          npm install -g @localstack/lstk
          lstk setup aws

      - name: Start LocalStack
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          DNS_ADDRESS: 0
        run: |
          docker pull localstack/localstack-pro:latest
          # Start LocalStack in the background
          LOCALSTACK_DEBUG=1 LOCALSTACK_AUTH_TOKEN=$LOCALSTACK_AUTH_TOKEN lstk start --non-interactive
          # Wait for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          lstk status
          echo "Startup complete"

      - name: Build the SAM application
        run: lstk sam build

      - name: Deploy the SAM application
        run: lstk sam deploy --resolve-s3 --no-confirm-changeset

      - name: List the resources
        run: |
          lstk aws sqs list-queues
          lstk aws sns list-topics
          lstk aws dynamodb list-tables
          lstk aws lambda list-functions
          lstk aws s3 ls

      - name: Send a Slack notification
        if: failure() || github.event_name != 'pull_request'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow run>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz
